import type { Metadata } from "next";
import { SiteHeader } from "@/components/marketing/site-header";
import { SiteFooter } from "@/components/marketing/site-footer";
import { Container } from "@/components/ui/container";

// Placeholder legal content — generic, not reviewed by a lawyer. Have this checked
// against UAE consumer-protection and real-estate brokerage regulations (and RERA/DLD
// requirements specifically) before relying on it. See the chat where this was added
// for the caveat; not shown on the page itself since a visible "not legal advice"
// banner would undercut the page's purpose.
export const metadata: Metadata = { title: "Terms of Service" };

const SECTIONS: { heading: string; body: string[] }[] = [
  {
    heading: "1. Acceptance of these terms",
    body: [
      "By accessing or using Qasro.com (\"Qasro\", \"we\", \"us\"), including creating an account, browsing listings, or submitting an enquiry, you agree to these Terms of Service. If you don't agree, please don't use the platform.",
    ],
  },
  {
    heading: "2. What Qasro is",
    body: [
      "Qasro is a real estate marketplace and intelligence platform for the UAE. We connect buyers, tenants, landlords, investors, agents, agencies and developers, and provide market data, valuations and an AI assistant to help you search and understand property listings.",
      "Qasro is not a party to any sale, lease, or other transaction arranged between users of the platform. We don't act as a broker, and listings are the responsibility of the agent, agency or developer who published them.",
    ],
  },
  {
    heading: "3. Accounts",
    body: [
      "You're responsible for the accuracy of the information you provide when creating an account, and for keeping your login credentials confidential. You're responsible for activity that happens under your account.",
      "Agent and agency accounts go through a manual verification step before they can publish listings. We may reject, suspend, or remove an account at our discretion, including for suspected fraud, misrepresentation, or violation of these terms.",
    ],
  },
  {
    heading: "4. Listings and data accuracy",
    body: [
      "Listings, prices, and property details are supplied by agents, agencies, developers, or connected third-party systems (including Vrodux, for agencies that connect their tenant). We don't independently verify every detail of every listing and don't guarantee its accuracy, availability, or completeness.",
      "Some content on the platform is clearly labeled \"Demo data\" for illustrative purposes and does not represent a real listing, transaction, or market figure.",
      "Market intelligence (valuations, price trends, comparables) is generated from available data and is an estimate, not a guarantee of a property's value or a substitute for professional advice.",
    ],
  },
  {
    heading: "5. Enquiries and lead sharing",
    body: [
      "When you submit an enquiry about a listing, your contact details and message are shared with the agent or agency responsible for that listing so they can respond to you. For agencies that connect their Vrodux CRM tenant to Qasro, your enquiry may also be forwarded into that agency's Vrodux tenant so their team can manage it there.",
    ],
  },
  {
    heading: "6. Acceptable use",
    body: [
      "You agree not to misuse the platform — including scraping or bulk-extracting data without permission, attempting to bypass account verification, submitting false or misleading listing information, or using the platform to send unsolicited commercial communications.",
    ],
  },
  {
    heading: "7. Third-party integrations",
    body: [
      "Qasro integrates with Vrodux, a separate CRM/ERP product, for agencies that choose to connect it. Vrodux and Qasro are separate systems with separate databases; connecting your Vrodux tenant is optional and controlled from your agency dashboard.",
    ],
  },
  {
    heading: "8. Limitation of liability",
    body: [
      "Qasro is provided \"as is.\" To the fullest extent permitted by law, we're not liable for losses arising from a transaction between users, inaccurate listing data, or reliance on market intelligence generated by the platform.",
    ],
  },
  {
    heading: "9. Changes to these terms",
    body: [
      "We may update these terms from time to time. Continued use of the platform after a change means you accept the updated terms.",
    ],
  },
  {
    heading: "10. Contact",
    body: ["Questions about these terms can be sent to hello@softaxis.ae."],
  },
];

export default function TermsPage() {
  return (
    <>
      <SiteHeader />
      <main className="flex-1 py-16">
        <Container className="max-w-2xl">
          <h1 className="text-2xl font-semibold text-ink-950">Terms of Service</h1>
          <p className="mt-2 text-sm text-sand-500">Last updated 30 September 2026</p>

          <div className="mt-8 space-y-8">
            {SECTIONS.map((section) => (
              <section key={section.heading}>
                <h2 className="font-semibold text-ink-950">{section.heading}</h2>
                {section.body.map((p, i) => (
                  <p key={i} className="mt-2 text-sm leading-relaxed text-sand-700">
                    {p}
                  </p>
                ))}
              </section>
            ))}
          </div>
        </Container>
      </main>
      <SiteFooter />
    </>
  );
}
